### PR TITLE
Added gerber files for jlcpcb

### PR DESCRIPTION
**Pull request by Sanic**
This PR adds a zip file containing the necessary gerber files for jlcpcb.

### CODE REVIEW

**Review by stapelberg — APPROVED** [review]

**Comment by stapelberg** [comment]
Thank you!

**Comment by deBaer** [comment]
Sadly, JLCPCB doesn't like the JLCPCB file.

Screenshot 2021-01-07 at 10 25 19

**Comment by Sanic** [comment]
Interesting!
My PCBs look OK and they didn't complain 😃 
So should the files be withdrawn and we wait for somebody to new have verified ones without X2?

**Comment by stapelberg** [comment]
Or could you do a re-export with the option changed as they are asking? Then perhaps @deBaer could do a test order?

**Comment by ProVeg-Simon** [comment]
I reexported without X2 und replaced the file in my order. I can of course share the Gerber files I sent them, but we could also wait until I get working boards based on that file delivered.

**Comment by stapelberg** [comment]
I have reverted the gerber commit for now.

Please send known-working files once you received the boards :) Thank you!

**Comment by ProVeg-Simon** [comment]
They're already drilling now, so they could read _something_ from my file. ;-)

**Comment by deBaer** [comment]
OK, the boards have arrived and they look beautiful and they work beautifully. 
84C06CDD-7472-4E2C-BFA5-68C47F066F36_1_105_c
This is the exact file I ordered them with:
[output2.zip](https://github.com/kinx-project/kint/files/5907206/output2.zip)

**Comment by stapelberg** [comment]
Thanks for reporting back! Could you send the gerbers as a pull request? That way, your contribution is correctly attributed.

Also, is it okay if I share your photo on twitter?

**Comment by ProVeg-Simon** [comment]
Sure, use it all you want. Also, here's a photo of the USB-A to USB-B adapter I hotglued into the gaping hole and plugged the Teensy pigtail into on the inside of the case.

IMG_1619(Edited)

PR for the Gerber coming up, and I'll send a very sweet layout for it to QMK soon-ish.

**Pull request merged**
