### PR TITLE
Create pcb_confirmed_working_on_JLCPCB.zip

### PR DESCRIPTION
**Pull request by deBaer**

### CODE REVIEW

**Comment by stapelberg** [comment]
Thanks for the PR! Could you move the file into gerbers/jlcpcb/ please, like https://github.com/kinx-project/kint/pull/20 did?

**Review by stapelberg — APPROVED** [review]

**Comment by afonsoguerra** [comment]
Is there any chance this can be updated to the latest PCB version (25-04-2021) ?

**Comment by stapelberg** [comment]
It would be great to add known-working gerbers for JLCPCB indeed, but note: the only change between the current JLCPCB gerbers, and revision 2021-04-25 is commit https://github.com/kinx-project/kint/commit/48328a4ce8c524a9bb49d2a999008e2705d4b4c1, which widens the slot cutouts ever so slightly to make the board cheaper to order at Aisler (no functional changes).

If you’re not ordering at Aisler, you can safely use the latest available gerbers.

**Comment by afonsoguerra** [comment]
Fantastic that the changes are not significant. Maybe it's not required to update it.

**Pull request merged**
